### PR TITLE
Added compatibility with latest django trunk

### PR DESCRIPTION
**Pull request by nemesifier**
The current code didn't work with the latest django trunk.
By adding a simple try-except statement I solved the issue.
It's a very small change.
Hope it helps.
Federico

### CODE REVIEW

**Comment by swiharta** [comment]
Sure would be nice if this got pulled.

**Comment by magopian** [comment]
doesn't it miss something more? Just changing the import isn't sufficient for the rest of the code (where the import is used), right?

**Comment by nemesifier** [comment]
for me that was enough to make it work.

**Comment by magopian** [comment]
you import "Feed" but you use "feed", surely, there's something missing. Maybe that's just a :

from django.contrib.syndication.views import Feed as feed

but i can't guarantee it, there's no tests to validate this, and i'm not 100% sure the new Feed (Class Based View) is totally compatible with the old deprecated "feed" view

**Comment by swiharta** [comment]
Come to think of it, I'm probably not even using django-notification for anything right now. All this change probably did was allow me to keep it in installed apps without throwing an error.

**Pull request closed without merging**
